server:
 port: 8080
spring:
 datasource:
  url: jdbc:mysql://root:Admin%4012345@localhost:3306/microServices
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password: Admin@12345
 h2:
  console:
   enable: true
 jpa:
  database-platform: org.hibernate.dialect.MySQLDialect
  hibernat:
   ddl-auto: update
  show-sql: true
 application:
  name: "accounts"
 config:
    import:
     - "optional:configserver:http://localhost:8071/"
 profiles:
    active:
    - "prod"
    
build:
  version: "3.0"
  
accounts:
  message: "Welcome to Accounts web service."
  contactDetails:
    name: "Onkar P"
    email: "onkarp@gmail.com"
  onCallSupport:
    -(222) 5555-5555
    -(222) 6666-6666
   
encrypt:
  key: "7B6A48BC8B35997517362D75ADDDE"
  
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
  

    

##spring.datasource.url=jdbc:mysql://root:Admin%4012345@localhost:3306/microServices
##spring.datasource.username=root
##spring.datasource.password=Admin@12345
##spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
##spring.application.name=account
##spring.jpa.show-sql= true
##spring.jpa.hibernate.ddl-auto=update
##spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect