server:
 port: 8080
spring:
 datasource:
  url: jdbc:mysql://root:Admin%4012345@localhost:3306/microServices
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password: Admin@12345
 h2:
  console:
   enable: true
 jpa:
  database-platform: org.hibernate.dialect.MySQLDialect
  hibernat:
   ddl-auto: update
  show-sql: true
 application:
  name: loans